### ISSUE TITLE
-o argument

### ISSUE THREAD

**Issue by desireBanse** [chepeftw/NS3DockerEmulator#2]
Hello.
It seems that you have removed the -o argument
`
parser.add_argument("operationStr", action="store",
                    help="The name of the operation to perform, options: full, create, destroy")
parser.add_argument("-n", "--number", action="store",
                    help="The number of nodes to simulate")
parser.add_argument("-t", "--time", action="store",
                    help="The time in seconds of NS3 simulation")
parser.add_argument('-v', '--version', action='version', version='%(prog)s 1.0')
`
How do you specify the action ("create or destroy") ?
Thank you.

**Comment by chepeftw** [comment]
Hi, first of all ... thank you very much for using the emulator, I'm glad to see that is being useful to other people 😄 ... second, I removed it indeed but now you can add it at the end of the call, for example:
python3 main.py -n 20 -t 200 create

I'm very sorry that on my last update I didn't update the README, which I will update since I have tons of other updates that I'm still pending to push. 

But please if you have any other question, let me know and I'll be happy to help.

**Comment by desireBanse** [comment]
Hello ,
Thank you very much for the quick answer. This is great tool, that I'm using for research purpose.

I'm getting a network unreachable when I ping one container from another (the first two). 
They are all using 10.12.0.x subnet.
I added to disable Ethernet filtering
`
cd /proc/sys/net/bridge
sudo -s
for f in bridge-nf-*; do echo 0 > $f; done
 exit
cd -
`
The NS-3 script is using a ad hoc Wifi .

Did you have the issue before ?

Thank you.

**Comment by chepeftw** [comment]
If you use the regular behavior the nodes will be moving by default, therefore sometimes they won't be reachable but from time to time they'll be in reach. I'm not sure I understand what you want to do by disabling ethernet filtering? Where are you running this exactly?

**Comment by desireBanse** [comment]
I'm running it on my laptop. It has Ubuntu 16.10.

I'm not longer using Ethernet filtering.

I would like to run the main.py script as is.

It seems that there are some network issues.
The NS-3 script in running fine : 
`
...
'build' finished successfully (5.414s)
Creating nodes
Creating wifi
Creating ad hoc wifi mac
Configuring physical layer
Configuring mobility
Allocation => ns3::GridPositionAllocator
Mobility => ns3::ConstantPositionMobilityModel
Creating tap bridges
Tap bridge = tap-emu1
Tap bridge = tap-emu2
Tap bridge = tap-emu3
Tap bridge = tap-emu4
Tap bridge = tap-emu5
Running simulation in wifi mode
`
When I attach to a container I can see that the IP is 10.12.0.x.x

`
root@93eff9548ce8:/data/golang/src/github.com/chepeftw/Beacon$ ifconfig
eth0      Link encap:Ethernet  HWaddr 12:34:d6:61:9d:87  
          inet addr:10.12.0.5  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:91 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:12817 (12.8 KB)  TX bytes:2968 (2.9 KB)
`

But, doing a network inspect, I have : 
`
[
    {
        "Name": "none",
        "Id": "8fceed24acc0363062bf8c02bfe76e60c28673d14c32983732186e32e4592e58",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "local",
        "Driver": "null",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "Containers": {
            "2bdaa1ad9d8c2140e2a58a0ddbc213438abafb5a1f19bc3158a40b70267e6566": {
                "Name": "emu2",
                "EndpointID": "cb313c580e78fed147937181e5f426c67b4ad46ab8266dba87ae3ec87a6b42e7",
                "MacAddress": "",
                "IPv4Address": "",
                "IPv6Address": ""
            },
            "74111d0ced7d154296037afe0950a8585f5f8d52e8382a6af2ae47236c5a33d9": {
                "Name": "emu1",
                "EndpointID": "65b23a6854df85c562601475e7a1154753110489b5ecf41d6a28f37c75e6956f",
                "MacAddress": "",
                "IPv4Address": "",
                "IPv6Address": ""
            },
            "7b35d12f2f40a92ad5f0c11ab57b8e7d992a749eab240042fbd2bcd6976a9839": {
                "Name": "emu3",
                "EndpointID": "c809cc98791dabdfa2f4072044a7bdbb72580dea31d73c487aca19a217f7d2c4",
                "MacAddress": "",
                "IPv4Address": "",
                "IPv6Address": ""
            },
            "93eff9548ce8640ac49789f9b13c4506e375d0cd3bab836a07d6006c1161e324": {
                "Name": "emu5",
                "EndpointID": "2a7c7b36faa244890a2490acbf2b4a81b08a4d45807573b1b6eef3b6e5942eb5",
                "MacAddress": "",
                "IPv4Address": "",
                "IPv6Address": ""
            },
            "da644f894a338f5bc28951fae7e9d54350537225916d5112b1395363d9dcd779": {
                "Name": "emu4",
                "EndpointID": "684dfb5f7699427bce3df114e2c38c5319d73e3319f60716710eceb93b0c6383",
                "MacAddress": "",
                "IPv4Address": "",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
`
The containers cannot see each other, nor are they accessible from the host (Whether the NS-3 script is running or not ).

Thank you.
