### ISSUE TITLE
Animation does work

### ISSUE THREAD

**Issue by qri-hub** [chepeftw/NS3DockerEmulator#6]
I saw on the documentation that the animation does not work. 
However it is possible to make it work doing the following : 
``
    #include "ns3/netanim-module.h" 
    // Insert the following 
   AnimationInterface anim ("path/to/file/tap-vm.xml"); 
   // Before the simulation starts  
   Simulator::Stop (Seconds (TotalTime)); 
   Simulator::Run (); 
   Simulator::Destroy (); 

``
![simu-tap-vm-adhoc](https://user-images.githubusercontent.com/3326804/44843485-b7701980-ac48-11e8-93c9-741cb84e348a.gif)

**Comment by chepeftw** [comment]
Hello, thanks a lot for that, indeed the last time (quite some time ago) I tried generating the animation it didn't work. Just for reference, which NS3 version are you using? Which version of PyViz and Python are you using? Thanks a lot for your feedback and contribution :).

**Comment by qri-hub** [comment]
No problem, 
- Python : 2.7.15rc1
- NS3 : 3.28
